using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace GirikGarg.PreferencesUtility.Editor
{
    /// <summary>
    /// Generates the C# accessor class for a definition. Output is deterministic (no timestamps, LF line endings),
    /// so regenerating an unchanged definition never produces a VCS diff or a recompile.
    /// </summary>
    public static class PrefsCodeGenerator
    {
        /// <summary>Tool name written into the header and <c>GeneratedCode</c> attribute.</summary>
        public const string GeneratorName = "Preferences Utility";

        /// <summary>Tool version written into the <c>GeneratedCode</c> attribute.</summary>
        public const string GeneratorVersion = "1.0.0";

        private const string AutoGeneratedMarker = "<auto-generated>";
        private const string ToolMarker = "This code was generated by " + GeneratorName;
        private const int HeaderProbeLength = 2048;
        private const int RemarksPreviewLength = 60;
        private const string Ellipsis = "...";
        private const string AllKeysField = "s_AllKeys";
        private const string EditorDefine = "UNITY_EDITOR";

        /// <summary>Generates the source code. The analysis must not contain errors.</summary>
        public static string Generate(PrefsDefinition definition, PrefsDefinitionAnalysis analysis, string assetPath)
        {
            if (analysis.HasErrors) throw new InvalidOperationException("Cannot generate code for a definition with errors.");

            bool isEditorPrefs = definition.storage == PrefsStorage.EditorPrefs;
            string prefsType = isEditorPrefs ? PrefsCodeConstants.EditorPrefsType : PrefsCodeConstants.PlayerPrefsType;
            string storageName = isEditorPrefs ? "EditorPrefs" : "PlayerPrefs";
            string className = analysis.ClassName;
            string namespaceName = definition.namespaceName.Trim();
            string accessModifier = definition.accessModifier == PrefsAccessModifier.Internal ? "internal" : "public";

            CodeWriter writer = new CodeWriter();
            WriteHeader(writer, assetPath);

            if (isEditorPrefs) writer.Line("#if " + EditorDefine);

            if (HasUnresolvedTypes(analysis))
            {
                writer.Line("using System;");
                writer.Line("using System.Collections.Generic;");
                writer.Line("using UnityEngine;");
                writer.Blank();
            }

            bool hasNamespace = !string.IsNullOrEmpty(namespaceName);
            if (hasNamespace)
            {
                writer.Line("namespace " + namespaceName);
                writer.Open();
            }

            writer.Line("/// <summary>");
            writer.Line($"/// Strongly typed <c>{storageName}</c> accessors generated from <c>{CSharpSyntax.XmlEscape(assetPath)}</c>.");
            writer.Line("/// </summary>");
            writer.Line("/// <remarks>This class is <c>partial</c>: add your own members in a separate file.</remarks>");
            writer.Line($"[global::System.CodeDom.Compiler.GeneratedCode({CSharpSyntax.StringLiteral(GeneratorName)}, {CSharpSyntax.StringLiteral(GeneratorVersion)})]");
            writer.Line($"{accessModifier} static partial class {className}");
            writer.Open();

            WriteKeys(writer, analysis, className);
            WriteDefaults(writer, analysis);
            WriteDefaultsJson(writer, analysis);
            WriteAllKeys(writer, analysis);

            for (int index = 0; index < analysis.Entries.Count; index++)
            {
                WriteProperty(writer, analysis.Entries[index], prefsType, storageName, definition.storage);
            }

            WriteHelpers(writer, prefsType, storageName, isEditorPrefs);

            writer.Close();
            if (hasNamespace) writer.Close();
            if (isEditorPrefs) writer.Line("#endif");

            return writer.ToString();
        }

        /// <summary>Returns true if the file at <paramref name="projectPath"/> carries this generator's header.</summary>
        public static bool IsGeneratedFile(string projectPath)
        {
            try
            {
                string fullPath = Path.GetFullPath(projectPath);
                if (!File.Exists(fullPath)) return false;

                char[] buffer = new char[HeaderProbeLength];
                int read;
                using (StreamReader reader = new StreamReader(fullPath, Encoding.UTF8, true))
                {
                    read = reader.ReadBlock(buffer, 0, buffer.Length);
                }

                string head = new string(buffer, 0, read);
                return head.Contains(AutoGeneratedMarker) && head.Contains(ToolMarker);
            }
            catch (IOException)
            {
                return false;
            }
            catch (UnauthorizedAccessException)
            {
                return false;
            }
        }

        /// <summary>Writes <paramref name="content"/> only if it differs from the file on disk. Returns true if the file changed.</summary>
        public static bool WriteIfChanged(string projectPath, string content)
        {
            string fullPath = Path.GetFullPath(projectPath);
            if (File.Exists(fullPath) && File.ReadAllText(fullPath, PrefsDefinitionSerializer.FileEncoding) == content) return false;

            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);

            File.WriteAllText(fullPath, content, PrefsDefinitionSerializer.FileEncoding);
            return true;
        }

        private static void WriteHeader(CodeWriter writer, string assetPath)
        {
            writer.Line("//------------------------------------------------------------------------------");
            writer.Line("// " + AutoGeneratedMarker);
            writer.Line("//     " + ToolMarker + " (com.girikgarg.preferencesutility).");
            writer.Line("//     Source definition: " + assetPath);
            writer.Line("//");
            writer.Line("//     Do not edit this file manually. Changes will be lost when the code is");
            writer.Line("//     regenerated. Open the source definition in the Preferences Utility");
            writer.Line("//     editor and save it to regenerate this file.");
            writer.Line("// </auto-generated>");
            writer.Line("//------------------------------------------------------------------------------");
            writer.Blank();
        }

        private static void WriteKeys(CodeWriter writer, PrefsDefinitionAnalysis analysis, string className)
        {
            writer.Line("/// <summary>Storage keys used by the properties of this class.</summary>");
            writer.Line("public static class Keys");
            writer.Open();
            foreach (PrefsEntryInfo info in analysis.Entries)
            {
                writer.Line($"/// <summary>Key of <see cref=\"{className}.{info.Entry.name}\"/>.</summary>");
                writer.Line($"public const string {info.Entry.name} = {CSharpSyntax.StringLiteral(info.Key)};");
            }

            writer.Close();
            writer.Blank();
        }

        private static void WriteDefaults(CodeWriter writer, PrefsDefinitionAnalysis analysis)
        {
            writer.Line("/// <summary>Values returned when a key is not set.</summary>");
            writer.Line("public static class Defaults");
            writer.Open();
            foreach (PrefsEntryInfo info in analysis.Entries)
            {
                string name = info.Entry.name;
                PrefsDefaultDeclaration declaration = info.Handler.GetDefaultDeclaration(info.ValueType);
                switch (declaration)
                {
                    case PrefsDefaultDeclaration.Const:
                        writer.Line($"public const {info.TypeExpression} {name} = {EmitDefault(info)};");
                        break;
                    case PrefsDefaultDeclaration.StaticReadonly:
                        writer.Line($"public static readonly {info.TypeExpression} {name} = {EmitDefault(info)};");
                        break;
                    default:
                        writer.Line($"/// <summary>A new instance of the default value of <c>{name}</c>.</summary>");
                        writer.Line($"public static {info.TypeExpression} {name} => " +
                                    $"{PrefsCodeConstants.JsonType}.ReadDefault<{info.TypeExpression}>(DefaultsJson.{name}, Keys.{name});");
                        break;
                }
            }

            writer.Close();
            writer.Blank();
        }

        private static void WriteDefaultsJson(CodeWriter writer, PrefsDefinitionAnalysis analysis)
        {
            List<PrefsEntryInfo> jsonEntries = analysis.Entries.FindAll(info =>
                info.Handler.GetDefaultDeclaration(info.ValueType) == PrefsDefaultDeclaration.Json);
            if (jsonEntries.Count == 0) return;

            writer.Line("/// <summary>Json of the default values of Json-serialized properties. Empty means <c>default</c>.</summary>");
            writer.Line("public static class DefaultsJson");
            writer.Open();
            foreach (PrefsEntryInfo info in jsonEntries)
            {
                writer.Line($"public const string {info.Entry.name} = {EmitDefault(info)};");
            }

            writer.Close();
            writer.Blank();
        }

        private static void WriteAllKeys(CodeWriter writer, PrefsDefinitionAnalysis analysis)
        {
            List<string> keyExpressions = analysis.Entries.ConvertAll(info => "Keys." + info.Entry.name);
            writer.Line($"private static readonly string[] {AllKeysField} = {{ {string.Join(", ", keyExpressions)} }};");
            writer.Blank();
            writer.Line("/// <summary>Every key declared by this class, in declaration order.</summary>");
            writer.Line($"public static global::System.Collections.Generic.IReadOnlyList<string> AllKeys => {AllKeysField};");
            writer.Blank();
        }

        private static void WriteProperty(CodeWriter writer, PrefsEntryInfo info, string prefsType, string storageName,
            PrefsStorage storage)
        {
            string name = info.Entry.name;
            PrefsEmitContext context = new PrefsEmitContext(prefsType, "Keys." + name, "Defaults." + name,
                "DefaultsJson." + name, info.TypeExpression);

            writer.Line("/// <summary>");
            if (string.IsNullOrWhiteSpace(info.Entry.summary))
            {
                writer.Line($"/// Gets or sets the <c>{CSharpSyntax.XmlEscape(info.Key)}</c> preference.");
            }
            else
            {
                foreach (string line in info.Entry.summary.Replace("\r\n", "\n").Split('\n'))
                {
                    writer.Line("/// " + CSharpSyntax.XmlEscape(line.TrimEnd()));
                }
            }

            writer.Line("/// </summary>");
            writer.Line($"/// <remarks>{storageName} key: <c>{CSharpSyntax.XmlEscape(info.Key)}</c>. " +
                        $"Default: <c>{CSharpSyntax.XmlEscape(PreviewDefault(info))}</c>.</remarks>");
            writer.Line($"public static {info.TypeExpression} {name}");
            writer.Open();
            writer.Line($"get => {info.Handler.EmitGetter(context, info.ValueType, storage)};");
            writer.Line($"set => {info.Handler.EmitSetter(context, info.ValueType, storage)};");
            writer.Close();
            writer.Blank();
        }

        private static void WriteHelpers(CodeWriter writer, string prefsType, string storageName, bool isEditorPrefs)
        {
            writer.Line($"/// <summary>Returns true if <paramref name=\"key\"/> exists in {storageName}.</summary>");
            writer.Line($"public static bool HasKey(string key) => {prefsType}.HasKey(key);");
            writer.Blank();
            writer.Line("/// <summary>Deletes <paramref name=\"key\"/>. Its property returns the default value afterwards.</summary>");
            writer.Line($"public static void DeleteKey(string key) => {prefsType}.DeleteKey(key);");
            writer.Blank();
            writer.Line($"/// <summary>Deletes every key declared by this class. Other {storageName} are not affected.</summary>");
            writer.Line("public static void DeleteAll()");
            writer.Open();
            writer.Line($"foreach (string key in {AllKeysField})");
            writer.Open();
            writer.Line($"{prefsType}.DeleteKey(key);");
            writer.Close();
            writer.Close();

            if (isEditorPrefs) return;

            writer.Blank();
            writer.Line("/// <summary>Writes modified PlayerPrefs to disk. Unity also saves automatically on quit.</summary>");
            writer.Line($"public static void Save() => {prefsType}.Save();");
        }

        private static string EmitDefault(PrefsEntryInfo info) =>
            info.Handler.EmitDefault(info.DefaultValue, info.ValueType, info.TypeExpression, info.Entry.defaultValue);

        private static string PreviewDefault(PrefsEntryInfo info)
        {
            string preview = info.Handler.Preview(info.DefaultValue, info.ValueType) ?? string.Empty;
            preview = preview.Replace('\n', ' ').Replace('\r', ' ');
            if (info.Handler.GetSlot(info.ValueType) == PrefsStorageSlot.String && !info.Handler.IsJson &&
                info.ValueType == typeof(string))
            {
                preview = "\"" + preview + "\"";
            }

            return preview.Length > RemarksPreviewLength ? preview.Substring(0, RemarksPreviewLength) + Ellipsis : preview;
        }

        private static bool HasUnresolvedTypes(PrefsDefinitionAnalysis analysis)
        {
            foreach (PrefsEntryInfo info in analysis.Entries)
            {
                if (info.Handler.UsesTypeName && info.ValueType == null) return true;
            }

            return false;
        }

        /// <summary>Minimal indented writer with LF line endings.</summary>
        private sealed class CodeWriter
        {
            private const string Indentation = "    ";
            private const char LineFeed = '\n';

            private readonly StringBuilder m_Builder = new StringBuilder();
            private int m_Depth;

            public void Line(string text)
            {
                bool isDirective = text.StartsWith("#", StringComparison.Ordinal);
                if (!isDirective)
                {
                    for (int i = 0; i < m_Depth; i++) m_Builder.Append(Indentation);
                }

                m_Builder.Append(text).Append(LineFeed);
            }

            public void Blank() => m_Builder.Append(LineFeed);

            public void Open()
            {
                Line("{");
                m_Depth++;
            }

            public void Close()
            {
                TrimTrailingBlankLine();
                m_Depth--;
                Line("}");
            }

            public override string ToString() => m_Builder.ToString();

            private void TrimTrailingBlankLine()
            {
                int length = m_Builder.Length;
                if (length >= 2 && m_Builder[length - 1] == LineFeed && m_Builder[length - 2] == LineFeed)
                {
                    m_Builder.Length = length - 1;
                }
            }
        }
    }
}
